"""
Configuration rendering engine for Cisco IOS-XE devices.
Generates actual CLI configuration from structured project data.

Each section produces:
- clean config lines (CLI commands only)
- annotated lines (with section comments explaining purpose)
- checklist items (what to verify before deployment)

IMPORTANT: Only generates commands that are explicitly mapped.
Unknown/uncertain features are marked as "needs verification".
"""

from datetime import datetime, timezone
from platform_profiles import (
    get_platform, get_features, is_feature_supported,
    is_l3_capable, is_industrial_platform
)


class ConfigRenderer:
    def __init__(self, project: dict):
        self.project = project
        self.device = project.get("device", {})
        self.mgmt = project.get("management", {})
        self.vlans = project.get("vlans", [])
        self.interfaces = project.get("interfaces", {})
        self.routing = project.get("routing", {})
        self.services = project.get("services", {})
        self.security = project.get("security", {})
        self.stp = project.get("stp", {})
        self.industrial = project.get("industrial", {})
        self.platform = self.device.get("platform_family", "")
        self.features = get_features(self.platform)
        self.profile = get_platform(self.platform) or {}

        self.clean_lines = []
        self.annotated_lines = []
        self.checklist = []

    def render(self) -> dict:
        """Generate all config outputs."""
        self._header()
        self._hostname()
        self._service_lines()
        self._aaa()
        self._local_users()
        self._domain_dns()
        self._vlans()
        self._stp()
        self._interfaces_access()
        self._interfaces_trunk()
        self._port_channels()
        self._svi()
        self._routing()
        self._management_interface()
        self._ntp()
        self._syslog()
        self._snmp()
        self._dhcp_relay()
        self._ssh_crypto()
        self._banner()
        self._line_console()
        self._line_vty()
        self._end()

        return {
            "clean_config": "\n".join(self.clean_lines),
            "annotated_config": "\n".join(self.annotated_lines),
            "checklist": self.checklist,
        }

    def _add(self, line, annotation=None):
        self.clean_lines.append(line)
        if annotation:
            self.annotated_lines.append(f"! >> {annotation}")
        self.annotated_lines.append(line)

    def _add_clean(self, line):
        self.clean_lines.append(line)
        self.annotated_lines.append(line)

    def _add_section(self, comment):
        self.clean_lines.append("!")
        self.annotated_lines.append("!")
        self.annotated_lines.append(f"! ===== {comment} =====")

    def _header(self):
        hostname = self.device.get("hostname", "UNNAMED")
        platform_name = self.profile.get("name", self.platform)
        os_ver = self.device.get("os_version", "unknown")
        ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

        self.annotated_lines.append("! Configuration generated by NetConfig Builder")
        self.annotated_lines.append(f"! Device: {hostname}")
        self.annotated_lines.append(f"! Platform: {platform_name} | IOS-XE {os_ver}")
        self.annotated_lines.append(f"! Role: {self.device.get('role', 'N/A')}")
        self.annotated_lines.append(f"! Generated: {ts}")
        if is_industrial_platform(self.platform):
            panel = self.industrial.get("panel_name", "")
            cabinet = self.industrial.get("cabinet_name", "")
            if panel or cabinet:
                self.annotated_lines.append(f"! Industrial: Panel={panel}, Cabinet={cabinet}")
        self.annotated_lines.append("!")

        self.checklist.append({
            "section": "Header",
            "item": f"Verify this config is for the correct device: {hostname} ({platform_name})",
            "type": "confirmation"
        })

    def _hostname(self):
        hostname = self.device.get("hostname", "").strip()
        if hostname:
            self._add_section("HOSTNAME")
            self._add(f"hostname {hostname}", "Sets the device hostname displayed in CLI prompt")
            self.checklist.append({"section": "Hostname", "item": f"Confirm hostname '{hostname}' matches naming convention", "type": "confirmation"})

    def _service_lines(self):
        self._add_section("SERVICE CONFIGURATION")
        self._add("service timestamps debug datetime msec localtime", "Timestamps on debug messages for troubleshooting correlation")
        self._add("service timestamps log datetime msec localtime", "Timestamps on log messages for syslog correlation")
        self._add("service password-encryption", "Encrypts plaintext passwords in running config (Type 7, weak but better than nothing)")
        self._add("no service pad", "Disables PAD service (legacy X.25, security best practice to disable)")

    def _aaa(self):
        aaa = self.security.get("aaa", {})
        self._add_section("AAA CONFIGURATION")

        if not aaa.get("enabled", True):
            self._add("aaa new-model", "AAA enabled with local-only defaults")
            self._add("aaa authentication login default local")
            self._add("aaa authorization exec default local")
            self.checklist.append({"section": "AAA", "item": "Verify AAA method matches site authentication policy", "type": "confirmation"})
            return

        self._add("aaa new-model", "Enables AAA framework for authentication and authorization")
        method = aaa.get("method", "local")

        if method != "radius":
            self._add("aaa authentication login default local", "Authenticate using local user database")
            self._add("aaa authorization exec default local", "Authorize exec sessions using local database")
            self.checklist.append({"section": "AAA", "item": "Verify AAA method matches site authentication policy", "type": "confirmation"})
            return

        if not is_feature_supported(self.platform, "aaa_radius"):
            self.annotated_lines.append("! WARNING: RADIUS AAA not supported on this platform")
            self._add("aaa authentication login default local", "Fallback: using local auth (RADIUS unsupported)")
            self._add("aaa authorization exec default local")
            self.checklist.append({"section": "AAA", "item": "Verify AAA method matches site authentication policy", "type": "confirmation"})
            return

        self._render_radius_servers(aaa.get("radius_servers", []))
        self._add("aaa authentication login default group radius local", "Authenticate via RADIUS, fallback to local")
        self._add("aaa authorization exec default group radius local")
        self.checklist.append({"section": "AAA", "item": "Verify AAA method matches site authentication policy", "type": "confirmation"})

    def _render_radius_servers(self, servers):
        for i, srv in enumerate(servers):
            ip = srv.get("ip", "").strip()
            if not ip:
                continue
            key = srv.get("key", "").strip()
            self._add(f"radius server RAD-{i+1}", f"RADIUS server {i+1}")
            self._add(f" address ipv4 {ip} auth-port 1812 acct-port 1813")
            if key:
                self._add(f" key {key}")

    def _local_users(self):
        users = self.security.get("local_users", [])
        if users:
            self._add_section("LOCAL USER ACCOUNTS")
            for user in users:
                uname = user.get("username", "").strip()
                priv = user.get("privilege", 15)
                if uname:
                    self._add(
                        f"username {uname} privilege {priv} algorithm-type scrypt secret <REPLACE_PASSWORD>",
                        f"Local user '{uname}' with privilege level {priv}. REPLACE password before deployment."
                    )
            self.checklist.append({
                "section": "Local Users",
                "item": "CRITICAL: Replace all <REPLACE_PASSWORD> placeholders with actual passwords before deployment",
                "type": "action_required"
            })

    def _domain_dns(self):
        domain = self.mgmt.get("domain_name", "").strip()
        dns_servers = [d.strip() for d in self.mgmt.get("dns_servers", []) if d.strip()]

        if domain or dns_servers:
            self._add_section("DOMAIN AND DNS")
        if domain:
            self._add(f"ip domain-name {domain}", "Required for SSH key generation and DNS resolution")
        for dns in dns_servers:
            self._add(f"ip name-server {dns}", "DNS server for name resolution")

    def _vlans(self):
        if not self.vlans:
            return
        self._add_section("VLAN CONFIGURATION")
        for vlan in self.vlans:
            vid = vlan.get("id")
            vname = vlan.get("name", "")
            if vid:
                self._add(f"vlan {vid}", f"VLAN {vid}: {vname or 'unnamed'}")
                if vname:
                    self._add(f" name {vname}")
        self.checklist.append({"section": "VLANs", "item": f"Verify {len(self.vlans)} VLANs match network design", "type": "confirmation"})

    def _stp(self):
        mode = self.stp.get("mode", "rapid-pvst")
        if is_feature_supported(self.platform, "stp_rapid_pvst") or is_feature_supported(self.platform, "stp_mst"):
            self._add_section("SPANNING-TREE")
            self._add(f"spanning-tree mode {mode}", f"STP mode: {mode}. Ensure all switches in the domain use the same mode.")
            priority = self.stp.get("priority", {})
            for vid, pri in priority.items():
                self._add(f"spanning-tree vlan {vid} priority {pri}", f"STP priority for VLAN {vid}")
            self.checklist.append({"section": "STP", "item": f"Confirm STP mode '{mode}' matches the network-wide standard", "type": "confirmation"})

    def _interfaces_access(self):
        ports = self.interfaces.get("access_ports", [])
        if not ports:
            return
        self._add_section("ACCESS PORT INTERFACES")
        for port in ports:
            intf = port.get("interface", "").strip()
            if not intf:
                continue
            desc = port.get("description", "").strip()
            vlan = port.get("vlan", "")
            voice_vlan = port.get("voice_vlan", "")

            self._add(f"interface {intf}", f"Access port: {desc or intf}")
            if desc:
                self._add(f" description {desc}")
            self._add(" switchport mode access")
            if vlan:
                self._add(f" switchport access vlan {vlan}")
            if voice_vlan:
                self._add(f" switchport voice vlan {voice_vlan}")
            if is_feature_supported(self.platform, "stp_portfast"):
                self._add(" spanning-tree portfast")
            if is_feature_supported(self.platform, "stp_bpduguard"):
                self._add(" spanning-tree bpduguard enable")
            self._add(" no shutdown")

    def _interfaces_trunk(self):
        ports = self.interfaces.get("trunk_ports", [])
        if not ports:
            return
        self._add_section("TRUNK PORT INTERFACES")
        for port in ports:
            intf = port.get("interface", "").strip()
            if not intf:
                continue
            desc = port.get("description", "").strip()
            allowed = port.get("allowed_vlans", "").strip()
            native = port.get("native_vlan", "")

            self._add(f"interface {intf}", f"Trunk port: {desc or intf}")
            if desc:
                self._add(f" description {desc}")
            # IOS-XE on modern platforms: no encapsulation command needed (dot1q only)
            if not self.profile.get("trunk_encapsulation", False):
                self.annotated_lines.append(f"! Note: trunk encapsulation dot1q is implicit on {self.profile.get('name', 'this platform')}")
            self._add(" switchport mode trunk")
            if allowed and allowed.lower() != "all":
                self._add(f" switchport trunk allowed vlan {allowed}")
            if native:
                self._add(f" switchport trunk native vlan {native}")
            self._add(" no shutdown")
        self.checklist.append({"section": "Trunk Ports", "item": "Verify trunk allowed VLANs match the uplink/downlink design", "type": "confirmation"})

    def _port_channels(self):
        pcs = self.interfaces.get("port_channels", [])
        if not pcs:
            return
        if not is_feature_supported(self.platform, "port_channel"):
            self.annotated_lines.append("! WARNING: Port-channel may not be supported on this platform. Needs verification.")
            return

        self._add_section("PORT-CHANNEL CONFIGURATION")
        for pc in pcs:
            self._render_pc_members(pc)
            self._render_pc_interface(pc)

        self.checklist.append({"section": "Port-Channels", "item": "Verify port-channel members and protocol (LACP/static) match peer device", "type": "confirmation"})

    def _render_pc_members(self, pc):
        pc_id = pc.get("id", "")
        desc = pc.get("description", "").strip()
        protocol = pc.get("protocol", "lacp")
        for member in pc.get("members", []):
            member = member.strip()
            if member:
                self._add(f"interface {member}", f"Port-channel {pc_id} member")
                if desc:
                    self._add(f" description {desc} (Po{pc_id} member)")
                self._add(f" channel-group {pc_id} mode active" if protocol == "lacp" else f" channel-group {pc_id} mode on")

    def _render_pc_interface(self, pc):
        pc_id = pc.get("id", "")
        mode = pc.get("mode", "trunk")
        allowed = pc.get("allowed_vlans", "").strip()
        desc = pc.get("description", "").strip()
        self._add(f"interface Port-channel{pc_id}", "Logical port-channel interface")
        if desc:
            self._add(f" description {desc}")
        if mode == "trunk":
            self._add(" switchport mode trunk")
            if allowed and allowed.lower() != "all":
                self._add(f" switchport trunk allowed vlan {allowed}")
        elif mode == "access":
            self._add(" switchport mode access")
            vlan = pc.get("vlan", "")
            if vlan:
                self._add(f" switchport access vlan {vlan}")
        self._add(" no shutdown")

    def _svi(self):
        svis = self.routing.get("svi_list", [])
        if not svis:
            return
        if not is_feature_supported(self.platform, "svi"):
            self.annotated_lines.append("! WARNING: SVIs not supported on this L2-only platform.")
            self.checklist.append({"section": "SVIs", "item": "SVIs were requested but platform does not support L3. Remove or change platform.", "type": "action_required"})
            return

        self._add_section("SVI (INTER-VLAN ROUTING) INTERFACES")
        if is_feature_supported(self.platform, "ip_routing"):
            self._add("ip routing", "Enable IP routing for inter-VLAN traffic")

        for svi in svis:
            vid = svi.get("vlan", "")
            ip = svi.get("ip", "").strip()
            mask = svi.get("mask", "").strip()
            desc = svi.get("description", "").strip()
            if vid and ip and mask:
                self._add(f"interface Vlan{vid}", f"SVI for VLAN {vid}")
                if desc:
                    self._add(f" description {desc}")
                self._add(f" ip address {ip} {mask}")
                self._add(" no shutdown")

        self.checklist.append({"section": "SVIs", "item": "Verify SVI IP addresses match the IP addressing plan", "type": "confirmation"})

    def _routing(self):
        routes = self.routing.get("static_routes", [])
        if not routes:
            return

        platform_profile = get_platform(self.platform)
        is_l2_only = platform_profile and platform_profile.get("layer", 2) == 2

        if is_l2_only:
            self._render_l2_default_gateway(routes)
            return

        if not is_feature_supported(self.platform, "static_routing"):
            self.annotated_lines.append("! WARNING: Static routing not supported. Skipping.")
            return

        self._render_static_routes(routes)

    def _render_l2_default_gateway(self, routes):
        # L2 switches use ip default-gateway instead of ip route
        for route in routes:
            if route.get("network", "").strip() == "0.0.0.0":
                self._add_section("DEFAULT GATEWAY (L2)")
                self._add(f"ip default-gateway {route.get('next_hop', '').strip()}",
                          "Default gateway for L2 switch management traffic")
                self.checklist.append({"section": "Default Gateway", "item": "Verify default gateway is reachable from management VLAN", "type": "confirmation"})

    def _render_static_routes(self, routes):
        self._add_section("STATIC ROUTES")
        for route in routes:
            network = route.get("network", "").strip()
            mask = route.get("mask", "").strip()
            next_hop = route.get("next_hop", "").strip()
            if network and mask and next_hop:
                self._add(f"ip route {network} {mask} {next_hop}",
                          f"Static route to {network}/{mask} via {next_hop}")

        self.checklist.append({"section": "Static Routes", "item": "Verify all static routes and next-hops are correct", "type": "confirmation"})

    def _management_interface(self):
        mgmt_vlan = self.mgmt.get("mgmt_vlan", "")
        mgmt_ip = self.mgmt.get("mgmt_ip", "").strip()
        mgmt_mask = self.mgmt.get("mgmt_mask", "").strip()
        gateway = self.mgmt.get("default_gateway", "").strip()

        if not mgmt_ip:
            return

        self._add_section("MANAGEMENT INTERFACE")

        platform_profile = get_platform(self.platform)
        is_l2_only = platform_profile and platform_profile.get("layer", 2) == 2

        if is_l2_only or not is_feature_supported(self.platform, "mgmt_ip_svi"):
            # L2 switch: use interface VlanX for management
            if mgmt_vlan:
                self._add(f"interface Vlan{mgmt_vlan}", "Management SVI for remote access")
                self._add(f" ip address {mgmt_ip} {mgmt_mask}")
                self._add(" no shutdown")
            if gateway:
                self._add(f"ip default-gateway {gateway}", "Default gateway for management traffic")
        else:
            # L3 switch: management is typically via SVI (already handled in SVI section)
            # Check if mgmt VLAN SVI already exists
            svis = self.routing.get("svi_list", [])
            mgmt_svi_exists = any(str(s.get("vlan", "")) == str(mgmt_vlan) for s in svis)
            if not mgmt_svi_exists and mgmt_vlan:
                self._add(f"interface Vlan{mgmt_vlan}", "Management SVI")
                self._add(f" ip address {mgmt_ip} {mgmt_mask}")
                self._add(" no shutdown")

        self.checklist.append({
            "section": "Management",
            "item": f"Verify management IP {mgmt_ip} is reachable and not conflicting with other devices",
            "type": "confirmation"
        })

    def _ntp(self):
        servers = [s.strip() for s in self.services.get("ntp_servers", []) if s.strip()]
        if not servers:
            return
        self._add_section("NTP")
        for srv in servers:
            self._add(f"ntp server {srv}", "Time synchronization source")
        self.checklist.append({"section": "NTP", "item": "Verify NTP servers are reachable from management VLAN", "type": "confirmation"})

    def _syslog(self):
        servers = [s.strip() for s in self.services.get("syslog_servers", []) if s.strip()]
        if not servers:
            return
        self._add_section("SYSLOG")
        self._add("logging buffered 64000", "Local logging buffer")
        for srv in servers:
            self._add(f"logging host {srv}", "Remote syslog destination")
        self.checklist.append({"section": "Syslog", "item": "Verify syslog servers are reachable and configured to receive logs", "type": "confirmation"})

    def _snmp(self):
        snmp = self.services.get("snmp", {})
        version = snmp.get("version", "")
        if not version:
            return

        self._add_section("SNMP")
        if version == "v2c":
            community = snmp.get("community", "").strip()
            if community:
                self._add(f"snmp-server community {community} RO", "SNMPv2c read-only community string")
                self.checklist.append({"section": "SNMP", "item": "Review SNMP community string security. Consider SNMPv3 for production.", "type": "confirmation"})
        elif version == "v3":
            user = snmp.get("v3_user", "").strip()
            auth_proto = snmp.get("v3_auth_protocol", "sha").lower()
            auth_pass = snmp.get("v3_auth_password", "").strip()
            priv_proto = snmp.get("v3_priv_protocol", "").lower()
            priv_pass = snmp.get("v3_priv_password", "").strip()

            if user and auth_pass:
                group_name = "SNMPV3-GRP"
                self._add(f"snmp-server group {group_name} v3 priv", "SNMPv3 group with authentication and privacy")
                cmd = f"snmp-server user {user} {group_name} v3 auth {auth_proto} {auth_pass}"
                if priv_proto and priv_pass:
                    cmd += f" priv {priv_proto} {priv_pass}"
                self._add(cmd, f"SNMPv3 user with auth ({auth_proto})")
                self.checklist.append({"section": "SNMP", "item": "SNMPv3 credentials are in config. Secure storage recommended.", "type": "confirmation"})

    def _dhcp_relay(self):
        entries = self.services.get("dhcp_relay", [])
        if not entries:
            return
        if not is_feature_supported(self.platform, "dhcp_relay"):
            self.annotated_lines.append("! WARNING: DHCP relay (ip helper-address) may not be supported on this platform. Needs verification.")
            return

        self._add_section("DHCP RELAY (IP HELPER-ADDRESS)")
        for entry in entries:
            vlan = str(entry.get("svi_vlan", "")).strip()
            helper = entry.get("helper_ip", "").strip()
            if not vlan or not helper:
                continue
            self._add(f"interface Vlan{vlan}", f"Add DHCP relay helper to VLAN {vlan} SVI")
            self._add(f" ip helper-address {helper}", f"Relay DHCP requests to {helper}")

        self.checklist.append({
            "section": "DHCP Relay",
            "item": "Verify DHCP server reachability from each relay SVI and helper-address ordering.",
            "type": "confirmation"
        })

    def _ssh_crypto(self):
        ssh = self.security.get("ssh", {})
        if not is_feature_supported(self.platform, "ssh"):
            return

        domain = self.mgmt.get("domain_name", "").strip()
        self._add_section("SSH AND CRYPTO")

        if not domain:
            self.annotated_lines.append("! WARNING: No domain name configured. SSH key generation requires a domain name.")
            self.annotated_lines.append("! Add: ip domain-name <your.domain> before generating RSA keys.")
            self.checklist.append({"section": "SSH", "item": "Domain name is required for SSH RSA key generation. Configure before deployment.", "type": "action_required"})

        rsa_bits = ssh.get("rsa_bits", 2048)
        self._add(f"crypto key generate rsa modulus {rsa_bits}", f"Generate {rsa_bits}-bit RSA key pair for SSH (run manually if needed)")
        self._add(f"ip ssh version {ssh.get('version', 2)}", "Enforce SSH version 2 only")
        if ssh.get("timeout"):
            self._add(f"ip ssh time-out {ssh['timeout']}")
        if ssh.get("retries"):
            self._add(f"ip ssh authentication-retries {ssh['retries']}")

    def _banner(self):
        banner = self.security.get("banner", "").strip()
        if banner:
            self._add_section("BANNER")
            self._add("banner login ^C", "Login banner displayed before authentication")
            for line in banner.split("\n"):
                self._add(line)
            self._add("^C")

    def _line_console(self):
        self._add_section("LINE CONSOLE")
        self._add("line con 0")
        self._add(" logging synchronous", "Prevent console messages from interrupting command input")
        self._add(" login local", "Require local authentication on console")

    def _line_vty(self):
        vty = self.security.get("line_vty", {})
        self._add_section("LINE VTY")
        self._add("line vty 0 15")
        transport = vty.get("transport", "ssh")
        self._add(f" transport input {transport}", f"Allow only {transport} for remote management")
        self._add(" login local", "Require local authentication for VTY access")
        acl = vty.get("access_class", "").strip()
        if acl:
            self._add(f" access-class {acl} in", f"Restrict VTY access to ACL {acl}")
        self.checklist.append({"section": "Line VTY", "item": f"VTY transport is set to '{transport}'. Verify this matches site security policy.", "type": "confirmation"})

    def _end(self):
        self._add_section("END")
        self._add_clean("end")
        self.checklist.append({
            "section": "Final Review",
            "item": "Review complete configuration before applying to device. Test in lab if possible.",
            "type": "action_required"
        })


def render_config(project: dict) -> dict:
    """Main entry point for config generation."""
    device = project.get("device", {})
    platform = device.get("platform_family", "")
    os_family = device.get("os_family", "")

    # C1200 (Cisco Small Business firmware) uses a different CLI syntax than
    # IOS-XE, so it is handled by a dedicated renderer.
    if os_family == "cisco_sb" or platform == "c1200":
        return _render_c1200(project)

    if platform == "wlc_9800":
        return _render_wlc_stub(project)

    renderer = ConfigRenderer(project)
    result = renderer.render()

    # Generate validation report summary
    result["validation_summary"] = _generate_validation_summary(project)
    return result


def _render_wlc_stub(project: dict) -> dict:
    """WLC config generation - limited support notice."""
    device = project.get("device", {})
    hostname = device.get("hostname", "WLC")

    lines = [
        "! WLC 9800 Configuration - LIMITED SUPPORT",
        f"! Device: {hostname}",
        "! NOTE: Full WLC config generation is not yet implemented.",
        "! Only basic management settings are rendered.",
        "!",
        f"hostname {hostname}",
    ]

    mgmt = project.get("management", {})
    if mgmt.get("domain_name"):
        lines.append(f"ip domain-name {mgmt['domain_name']}")
    for dns in mgmt.get("dns_servers", []):
        if dns.strip():
            lines.append(f"ip name-server {dns.strip()}")

    for ntp in project.get("services", {}).get("ntp_servers", []):
        if ntp.strip():
            lines.append(f"ntp server {ntp.strip()}")

    lines.append("!")
    lines.append("! WLC-specific WLAN/SSID/policy configuration is not implemented yet.")
    lines.append("! This section requires manual configuration or future tool support.")
    lines.append("!")
    lines.append("end")

    config_text = "\n".join(lines)
    return {
        "clean_config": config_text,
        "annotated_config": config_text,
        "checklist": [
            {"section": "WLC", "item": "WLC config generation is limited. Most settings require manual configuration.", "type": "action_required"},
            {"section": "WLC", "item": "Configure WLAN profiles, policy profiles, and policy tags manually.", "type": "action_required"},
        ],
        "validation_summary": "WLC configuration generation is limited in this release. Only basic management settings are rendered."
    }


def _generate_validation_summary(project: dict) -> str:
    """Generate a brief summary for the validation report tab."""
    device = project.get("device", {})
    vlans = project.get("vlans", [])
    access = project.get("interfaces", {}).get("access_ports", [])
    trunks = project.get("interfaces", {}).get("trunk_ports", [])
    svis = project.get("routing", {}).get("svi_list", [])

    parts = [
        f"Platform: {device.get('platform_family', 'unknown')} | IOS-XE {device.get('os_version', 'unknown')}",
        f"VLANs: {len(vlans)}",
        f"Access ports: {len(access)}",
        f"Trunk ports: {len(trunks)}",
        f"SVIs: {len(svis)}",
    ]
    return " | ".join(parts)


# ============================================================================
# C1200 (Cisco Catalyst 1200) renderer - Small Business firmware, NOT IOS-XE
# CLI syntax confirmed against the official C1200 CLI Guide (rev 2025-09).
# Key differences from IOS-XE:
#   - interfaces: gi1/0/1 abbreviation, slot always 0
#   - VLANs created inside 'vlan database' mode: 'vlan N name X'
#   - trunk allowed list uses 'switchport trunk allowed vlan add'
#   - time sync via SNTP (not NTP); SNMP RO uses lowercase 'ro'
#   - 'ip domain name' (space) vs IOS-XE 'ip domain-name'
#   - local users: 'username X password ... privilege N' (no scrypt/secret)
#   - STP priority is GLOBAL (no per-VLAN priority)
#   - no IP routing / SVI routing / HSRP / VRRP / DHCP relay
# ============================================================================

import re as _c1200_re

_C1200_IF_ABBR = [
    ("TwoPointFiveGigabitEthernet", "tw"),
    ("FiveGigabitEthernet", "fi"),
    ("TenGigabitEthernet", "te"),
    ("FortyGigabitEthernet", "fo"),
    ("TwentyFiveGigE", "twe"),
    ("GigabitEthernet", "gi"),
    ("FastEthernet", "fa"),
    ("Port-channel", "po"),
    ("Port-Channel", "po"),
]


def _c1200_ifname(name: str) -> str:
    """Convert an IOS-XE style interface name to C1200 abbreviation.
    'GigabitEthernet1/0/1' -> 'gi1/0/1'. Leaves already-short names as-is."""
    if not name:
        return name
    n = name.strip()
    for full, abbr in _C1200_IF_ABBR:
        if n.startswith(full):
            return abbr + n[len(full):]
    return n


def _render_c1200(project: dict) -> dict:
    """Render configuration for Cisco Catalyst 1200 (Small Business firmware)."""
    device = project.get("device", {})
    mgmt = project.get("management", {})
    vlans = project.get("vlans", [])
    interfaces = project.get("interfaces", {})
    services = project.get("services", {})
    security = project.get("security", {})
    stp = project.get("stp", {})
    hostname = device.get("hostname", "SWITCH")

    clean, ann, checklist = [], [], []

    def add(line, note=None):
        clean.append(line)
        if note:
            ann.append(f"! >> {note}")
        ann.append(line)

    def sect(title):
        clean.append("!")
        ann.append("!")
        ann.append(f"! ===== {title} =====")

    def note_both(text):
        clean.append(text)
        ann.append(text)

    def chk(section, item, ctype="confirmation"):
        checklist.append({"section": section, "item": item, "type": ctype})

    # ---- Annotated header ----
    ann.append("! Configuration generated by NetConfig Builder")
    ann.append(f"! Device: {hostname} (Cisco Catalyst 1200 - SMB firmware, NOT IOS-XE)")
    ann.append(f"! Platform: c1200 | Firmware {device.get('os_version', '4.x')}")
    ann.append("!")
    chk("Header", f"Verify this config is for the correct device: {hostname} (Cisco Catalyst 1200, SMB firmware)")

    # ---- Hostname ----
    sect("HOSTNAME")
    add(f"hostname {hostname}", "Device hostname")

    # ---- Domain / DNS ----
    if mgmt.get("domain_name") or any((d or "").strip() for d in mgmt.get("dns_servers", [])):
        sect("DOMAIN AND DNS")
        if mgmt.get("domain_name"):
            add(f"ip domain name {mgmt['domain_name']}",
                "Domain name (C1200 uses 'ip domain name' with a space, not IOS-XE 'ip domain-name')")
        for dns in mgmt.get("dns_servers", []):
            if (dns or "").strip():
                add(f"ip name-server {dns.strip()}", "DNS server")

    # ---- Local users ----
    users = security.get("local_users", [])
    if users:
        sect("LOCAL USER ACCOUNTS")
        for u in users:
            priv = u.get("privilege", 15)
            add(f"username {u['username']} password <REPLACE_PASSWORD> privilege {priv}",
                f"Local user '{u['username']}'. C1200 uses 'password' (no scrypt/secret). REPLACE before deploy.")
        chk("Local Users", "CRITICAL: Replace all <REPLACE_PASSWORD> placeholders before deployment", "action_required")

    # ---- VLANs (vlan database mode) ----
    if vlans:
        sect("VLAN CONFIGURATION (vlan database mode)")
        add("vlan database", "Enter VLAN database mode (C1200-specific)")
        for v in vlans:
            name = (v.get("name") or "").strip()
            if name:
                add(f"vlan {v['id']} name {name}", f"VLAN {v['id']}: {name}")
            else:
                add(f"vlan {v['id']}", f"VLAN {v['id']}")
        add("exit", "Exit VLAN database mode")
        chk("VLANs", f"Verify {len(vlans)} VLANs match network design")

    # ---- Spanning-tree ----
    if stp:
        sect("SPANNING-TREE")
        mode = stp.get("mode", "rapid-pvst")
        add(f"spanning-tree mode {mode}",
            f"STP mode: {mode} (C1200 supports stp/rstp/mst/pvst/rapid-pvst)")
        prio = stp.get("priority", {}) or {}
        if prio:
            try:
                lowest = sorted(int(p) for p in prio.values())[0]
            except (ValueError, TypeError):
                lowest = list(prio.values())[0]
            add(f"spanning-tree priority {lowest}",
                "C1200 STP priority is GLOBAL (per-VLAN priority is not supported)")
            chk("STP", "C1200 uses a single GLOBAL STP priority; per-VLAN priorities were "
                       "collapsed to the lowest value. Verify this is acceptable.", "action_required")

    # ---- Access ports ----
    access = interfaces.get("access_ports", [])
    if access:
        sect("ACCESS PORTS")
        for p in access:
            ifn = _c1200_ifname(p.get("interface", ""))
            add(f"interface {ifn}", f"Access port: {p.get('description', '')}")
            if p.get("description"):
                add(f" description {p['description']}")
            add(" switchport mode access")
            add(f" switchport access vlan {p.get('vlan')}")
            add(" spanning-tree portfast")
        chk("Access Ports", f"Verify {len(access)} access ports and VLAN assignments")

    # ---- Trunk ports ----
    trunks = interfaces.get("trunk_ports", [])
    if trunks:
        sect("TRUNK PORTS")
        for t in trunks:
            ifn = _c1200_ifname(t.get("interface", ""))
            add(f"interface {ifn}", f"Trunk port: {t.get('description', '')}")
            if t.get("description"):
                add(f" description {t['description']}")
            add(" switchport mode trunk")
            if t.get("allowed_vlans"):
                add(f" switchport trunk allowed vlan add {t['allowed_vlans']}",
                    "C1200 uses 'allowed vlan add' to add VLANs to the trunk")
            if t.get("native_vlan"):
                add(f" switchport trunk native vlan {t['native_vlan']}")
        chk("Trunk Ports", "Verify trunk allowed VLANs match the uplink/downlink design")

    # ---- Port channels (limited) ----
    pcs = interfaces.get("port_channels", [])
    if pcs:
        sect("PORT CHANNELS (LIMITED)")
        note_both("! Port-channel (LAG) rendering for C1200 is not implemented in this release.")
        note_both("! Configure LAGs manually: 'interface po1' / 'channel-group' equivalents per CLI guide.")
        chk("Port-Channels", "Port-channel (LAG) config for C1200 must be done manually in this release.", "action_required")

    # ---- Management interface (L2 mgmt SVI only) ----
    if mgmt.get("mgmt_vlan") and mgmt.get("mgmt_ip"):
        sect("MANAGEMENT INTERFACE")
        add(f"interface vlan {mgmt['mgmt_vlan']}", "Management VLAN interface")
        add(f" ip address {mgmt['mgmt_ip']} {mgmt.get('mgmt_mask', '255.255.255.0')}")
        if mgmt.get("default_gateway"):
            add(f"ip default-gateway {mgmt['default_gateway']}", "Default gateway (L2 switch)")
        chk("Management", f"Verify management IP {mgmt['mgmt_ip']} is reachable and non-conflicting")

    # ---- SNTP (time) ----
    ntps = [s for s in services.get("ntp_servers", []) if (s or "").strip()]
    if ntps:
        sect("SNTP (TIME SYNC)")
        add("sntp unicast client enable", "Enable SNTP client (C1200 uses SNTP, not NTP)")
        for s in ntps:
            add(f"sntp server {s.strip()}", "SNTP time source")

    # ---- Syslog ----
    sl = [s for s in services.get("syslog_servers", []) if (s or "").strip()]
    if sl:
        sect("SYSLOG")
        for s in sl:
            add(f"logging host {s.strip()}", "Remote syslog server")

    # ---- SNMP ----
    snmp = services.get("snmp", {})
    if snmp.get("version") == "v2c" and snmp.get("community"):
        sect("SNMP")
        add(f"snmp-server community {snmp['community']} ro",
            "SNMPv2c RO community (C1200 uses lowercase ro/rw/su)")
        chk("SNMP", "Review SNMP community security. Consider SNMPv3 for production.")
    elif snmp.get("version") == "v3" and snmp.get("v3_user"):
        sect("SNMP (V3 - MANUAL)")
        note_both("! SNMPv3 on C1200 requires snmp-server user/group/view setup - configure manually.")
        chk("SNMP", "SNMPv3 for C1200 needs manual snmp-server user/group/view config.", "action_required")

    # ---- SSH ----
    sect("SSH")
    add("crypto key generate rsa", "Generate RSA key pair for SSH (run manually if prompted)")
    add("ip ssh server", "Enable the SSH server")

    # ---- Management lines ----
    sect("MANAGEMENT LINES")
    add("line ssh", "SSH line configuration")
    add(" login authentication default", "Use local authentication for SSH")

    # ---- Banner (not supported via CLI on C1200) ----
    if security.get("banner"):
        chk("Banner", "Login banner via CLI is not available on C1200; set it in the web UI if required.")

    # ---- End ----
    note_both("!")
    ann.append("! ===== END =====")
    clean.append("end")
    ann.append("end")

    chk("Final Review", "C1200 uses non-IOS-XE (Small Business) syntax. Review and lab-test before production.", "action_required")

    return {
        "clean_config": "\n".join(clean),
        "annotated_config": "\n".join(ann),
        "checklist": checklist,
        "validation_summary": (
            f"Platform: c1200 (SMB firmware, non-IOS-XE) | VLANs: {len(vlans)} | "
            f"Access: {len(access)} | Trunk: {len(trunks)} | "
            f"Routing: N/A (L2 only)"
        ),
    }
